[package]
name = "iavl-app"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "1.1.0", features = ["rlp"] }
alloy-rlp = { version = "0.3.11", features = ["derive"] }
bincode = "2.0.1"
iavl = { path = "../iavl" }
